"""New fields in user model

Revision ID: 558566f8c647
Revises: a9ee534b492b
Create Date: 2019-12-10 14:46:30.154261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558566f8c647'
down_revision = 'a9ee534b492b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
