"""Add language to posts

Revision ID: e82f64dbb502
Revises: 3e497dad037f
Create Date: 2019-12-21 20:20:20.359772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82f64dbb502'
down_revision = '3e497dad037f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.String(length=5), nullable=True))
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language')
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
